### PR TITLE
fix(*): update action func to adhere to codegangsta 1.15.0 spec

### LINKED ISSUE #33: need to update cli
Getting the following deprecation warning when we run deisrel:

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

### PR DESCRIPTION
**Pull request by sgoings**
Fixes #33

### CODE REVIEW

**Comment by arschles** [comment]
@sgoings out of curiosity, what happens if one of the action funcs returns a non-nil `error`?

**Comment by sgoings** [comment]
From what I could see... we were running `log.Fatalf` on every error handling case... which would exit early.

**Comment by arschles** [comment]
yep, we are. just was curious what happens if you return an error instead of exiting cleanly. either's fine with me fwiw

**Comment by sgoings** [comment]
@arschles you're the Go master. What is preferable?

**Comment by arschles** [comment]
the way we're doing it now works just fine for me. plus it minimizes the changes in this patch

**Pull request merged**
