### PR TITLE
fix(changelog): fix broken changelog template

### LINKED ISSUE #133: panic when running deisrel
```
$ deisrel
panic: template: changelog:3: illegal number syntax: "-"

goroutine 1 [running]:
text/template.Must(0x0, 0xca0000, 0xc820066e90, 0x0)
       	/usr/local/go/src/text/template/helper.go:23 +0x4b
github.com/deis/deisrel/changelog.init()
       	/Users/bacongobbler/go/src/github.com/deis/deisrel/changelog/changelog.go:48 +0xc3
github.com/deis/deisrel/actions.init()
       	/Users/bacongobbler/go/src/github.com/deis/deisrel/actions/generate_individual_changelog.go:72 +0x54
main.init()
       	/Users/bacongobbler/go/src/github.com/deis/deisrel/main.go:145 +0x59

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
       	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

### PR DESCRIPTION
**Pull request by bacongobbler**
closes #133

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
Hmm. This wasn't a problem on my computer. It prevents an unintentional newline in the changelogs.

**Comment by bacongobbler** [comment]
Ah wait maybe this is a Go 1.6 feature? I'm on 1.5.1 on my laptop. Let me try upgrading.

**Comment by Joshua-Anderson** [comment]
Yeah, I belive this landed in 1.6 or 1.7.

**Comment by bacongobbler** [comment]
Indeed, upgrading to 1.6 fixed this for me.

**Pull request closed without merging**
