### PR TITLE
feat(build): Limit cross-compilation to darwin/amd64 and linux/amd64

### LINKED ISSUE #94: Limit cross-compilation to just darwin/amd64 and linux/amd64
These two combinations should sufficiently cover anyone who might actually coordinate a release of Workflow (i.e. the deis team). There's no reason to build all the other os/arch permutations and allow them to take up space in GCS if they will never be used.

### PR DESCRIPTION
**Pull request by krancour**
Closes #94

### CODE REVIEW

**Comment by bacongobbler** [comment]
we'll just have to make sure to purge the -latest releases that are not linux or darwin amd64 from GCS after merging this.

**Comment by krancour** [comment]
> we'll just have to make sure to purge the -latest releases that are not linux or darwin amd64 from GCS after merging this.

@bacongobbler you know how to do that? I can't seem to find the bucket in question. I'm guessing it's not in our sandbox account-- which is the only GCP account of ours I have access to atm.

**Comment by arschles** [comment]
@krancour It's located in the `deis-downloads` project. I just gave you access as an admin

**Comment by krancour** [comment]
@arschles thanks. @bacongobbler this bit of post-merge maintenance you suggested is all taken care of now.

**Comment by arschles** [comment]
@krancour not sure if you care, but some of the older SHA releases have the entire cross-compiled suite. For example: https://storage.googleapis.com/deisrel/git-3fb96a0/deisrel-git-3fb96a0-netbsd-386 or https://storage.googleapis.com/deisrel/git-32c8c3a/deisrel-git-32c8c3a-openbsd-386. I'm not worried if these don't get removed, but just wanted to make you aware they're out there.

**Comment by krancour** [comment]
Yep. I'm fine with those sticking around too.  I think the concern was just about removing "latest" for OS / arch combos we're not supporting. Someone looking for those could download them without realizing just how stale they were.

**Pull request merged**
